# Array and array methods
from  array import *
# sample of an array
a=array('i',[10,20,30,40])
print(a)
print(type(a))
print("creating an empty array")
b=array('i',[])
print(b)
print("Accessing one 1D array")
print(a[0])
print("Accessing using for loop")
print("without using index")
for i in a:
    print(i,end=" ")
print()
print("with index")
for i in range(len(a)):
    print(a[i],end=" ")
print()
print("While loop")
i=0
while i<len(a):
    print(a[i],end=" ")
    i+=1
print()
print("index()")
a2=array('i',[10,20,10,30,190])
print(a2.index(10))
print("insert()")
a2.insert(2,40)
print(a2)
print("reverse()")
a2.reverse()
print(a2)
print("append()")
a2.append(23)
print(a2)
print("pop()")
t=a2.pop()
print("poped element:",t)
print(a2)
print("pop(n)")
t=a2.pop(0)
print("poped element:",t)
print(a2)
print("remove()")
a2.remove(10)
print(a2)
print("extend()")
print("Extended by array")
ar=a2.extend(a)
print(a2)
print("Extended by set")
a2.extend({11,22,44,66,77})
print(a2)
print("Extended by list")
a2.extend([100,200,300])
print(a2)
print("Extended by dic")
a2.extend({1:"a",2:"b"})
print(a2)
print("\n*******UserInput Array********")
n=int(input("Enter No.of Elements"))
a=array('i',[])
for i in range(n):
    a.append(int(input("Enter number:")))
for i in a:
    print(i,end=" ")