# ------------------List-method---------------------
print("-------insert(pos_num,ele)-------")
l=[12,2.4,"kkk"]
l.insert(3,40)
print(l)
print("-------insert(pos_num,ele)-------")
l=[12,2.4,"kkk"]
l.insert(3,40)
print(l)
print()

print("----------------pop()---------------")
l=[12,2.4,"kkk"]
p=l.pop()
print(p)
print(l)
print("----------------pop(position)---------------")
l=[12,2.4,"kkk"]
p=l.pop(0)
print(p)
print(l)
print("----------------remove(ele)---------------")
l=[10,20,30,40]
l.remove(10)
print(l)
print("----------------index(ele)---------------")
l=[10,20,30,40]
p=l.index(30)
print(p)
print("----------------reverse()---------------")
l=[10,20,30,40]
l.reverse()
print(l)
print("----------------extend()---------------")
l=[10,20,30,40]
b=[12,13,13]
l.extend(b)
print(l)
l.extend("lava")
print(l)
print("----------------count(ele)---------------")
p="Lavaanya"
q=list(p)
q.reverse()
print(q.count('a'))
print("----------------sort()---------------")
l=[23,45,7,89,12]
l.sort()
print(l)
print("----------------clear()---------------")
l=[23,45,7,89,12]
l.clear()
print(l)
l.append(10)
print(l)
print("----------------Repetition Of List *---------------")
l=['l','s','m']
print(l*2)
print("----------------concatination + ---------------")
l=['l','s','m']
p=['m','n','n']
print(l+p)
print("----------------Alisiong List---------------")
l=['l','s','m']
p=l
print(p,id(p))
print(l,id(l))
l[1]='n'
print(l,id(l))
print(p,id(p))
p[0]='m'
print(l,id(l))
print(p,id(p))
print("----------------copy()---------------")
a=[10,20,30]
# b=[23,34,55]
b=a.copy()
print(b,id(b))
print(a,id(a))
a[1]=34
print(a,id(a))
print(b,id(b))
print("----------------copy()---------------")
a=[10,20,30]
b=a[:]
print(b,id(b))
print(a,id(a))
a[1]=34
print(a,id(a))
print(b,id(b))
print("---------------List()----------------")
print("creating empty list")
p=list()
print(p)
print("Tuple list")
r=(10,20,30,40)
q=list(r)
print(q)
print("String")
s=list("Lavanya")
print(s)
print("range")
r=list(range(1,5))
print(r)
