#-----------------------attributes---------------------
from numpy import *
print("sample of 2d array")
a=array([[10,20,30],
         [40,50,60]])
print(a)
print("for 2d array")
print("********ndim************")
print(a.ndim)
print("********shape************")
print(a.shape)
print("**********size************")
print(a.size)
print("********itemsize************")
print(a.itemsize)
print("********nbytes************")
print(a.nbytes)
b=array([10,20,30,40,50,60])
print(b)
print("for 1d array")
print("********ndim************")
print(b.ndim)
print("********shape************")
print(b.shape)
print("********size************")
print(b.size)
print("********itemsize************")
print(b.itemsize)
print("********nbytes************")
print(b.nbytes)
