# ********** Formating String **********
print("                        -----------------------Integer Type---------------------")
print("{}".format(10))
print("{0}".format(10))
print("{name}".format(name=10))
print("{}   {}".format(10,20))
print("{0}   {1}".format(10,20))
print("{1}   {0}".format(10,20))
print("{num1}   {num2}".format(num1=10,num2=20))
print("HEllO My Name is {} And My Age Is {}".format("Lavanya",20))

print("----------Integer Type Formating--------")
print("{:d}".format(10))
print("{0:d}".format(10))
print("{0:d} {1:d}".format(10,20))
print("{num:d}".format(num=10))
print("----------Width----------")
print("{num:5d}".format(num=15))
print("----------Padding 0----------")
print("{num:05d}".format(num=15))
print("----------Left align----------")
print("{num:<5d}".format(num=15))
print("----------Left align with padding 0----------")
print("{num:<05d}".format(num=15))
print("----------Left align and fill with *----------")
print("{num:*<5d}".format(num=15))
print("----------Sign------------")
print("{num:+5d}".format(num=15))
print("----------Sign with left align----------")
print("{num:<+5d}".format(num=15))
print("----------right align----------")
print("{num:>5d}".format(num=15))
print("----------right align padding----------")
print("{num:>05d}".format(num=15))
print("----------right align and fill with *----------")
print("{num:*>5d}".format(num=15))
print("----------center align----------")
print("{num:^5d}".format(num=15))
print("----------center align and fill with *----------")
print("{num:*^5d}".format(num=15))
print()
print()
print("-------------------------------------------------------------------------------------------------------------")
print("-------------------------------------------------------------------------------------------------------------")
# ********** Formating String 2 **********
print()
print("                        -----------------------Floating Type---------------------")
print("{}".format(10.56))
print("{0}".format(10.56))
print("{name}".format(name=10.56))
print("{}   {}".format(10.56,20.35))
print("{0}   {1}".format(10.56,20.35))
print("{1}   {0}".format(10.56,20.35))
print("{num1}   {num2}".format(num1=10.56,num2=20.35))
print("HEllO My Name is {} And My Age Is {}".format("Lavanya",20.1))
print("----------Floating Type Formating--------")
print("{:f}".format(10.56))
print("{0:f}".format(10.56))
print("{0:f} {1:f}".format(10.56,20.35))
print("{num:f}".format(num=15.65))
print("----------Width----------")
print("{num:8f}".format(num=15.65))
print("----------.presicion----------")
print("{num:8.3f}".format(num=15.65))
print("----------Padding 0----------")
print("{num:08.2f}".format(num=15.65))
print("----------Left align----------")
print("{num:<8.2f}".format(num=15.65))
print("----------Left align and padding with 0----------")
print("{num:<08.2f}".format(num=15.65))
print("----------Left align and fill with *----------")
print("{num:*<8.2f}".format(num=15.65))
print("----------Sign----------")
print("{num:+8.2f}".format(num=15.65))
print("----------Sign with left align----------")
print("{num:<+8.2f}".format(num=15.65))
print("----------right align----------")
print("{num:>8.2f}".format(num=15.65))
print("----------right align padding----------")
print("{num:>08.2f}".format(num=15.65))
print("----------right align and fill with *----------")
print("{num:*>8.2f}".format(num=15.65))
print("----------center align----------")
print("{num:^8.2f}".format(num=15.65))
print("----------center align and fill with *----------")
print("{num:*^8.2f}".format(num=15.65))
print()
print()
print("-------------------------------------------------------------------------------------------------------------")
print("-------------------------------------------------------------------------------------------------------------")
# ********** Formating String 3 **********
print()
print("                        -----------------------String Type---------------------")
print("{}".format("Geeky"))
print("{0}".format("Geeky"))
print("{name}".format(name="Geeky"))
print("{}   {}".format("Geeky","Shows"))
print("{0}   {1}".format("Geeky","Shows"))
print("{1}   {0}".format("Geeky","Shows"))
print("{num1}   {num2}".format(num1="Geeky",num2="Shows"))
print("HEllO My Name is {} And My Age Is {}".format("Lavanya",20.1))
print()
print("----------String Type Formating--------")
print("{:s}".format("Geeky"))
print("{0:s}".format("Geeky"))
print("{0:s} {1:s}".format("Geeky","shows"))
print("{num:s}".format(num="Geeky"))
print("----------Width----------")
print("{num:8s}".format(num="Geeky"))
print("----------.presicion----------")
print("{num:.3s}".format(num="Geeky"))
print("----------Left align----------")
print("{num:<8.3s}".format(num="Geeky"))
print("----------Left align and padding with 0----------")
print("{num:<08.3s}".format(num="Geeky"))
print("----------Left align and fill with *----------")
print("{num:*<8.3s}".format(num="Geeky"))
print("----------right align----------")
print("{num:>8.3s}".format(num="Geeky"))
print("----------right align padding----------")
print("{num:>08.3s}".format(num="Geeky"))
print("----------right align and fill with *----------")
print("{num:*>8.3s}".format(num="Geeky"))
print("----------center align----------")
print("{num:^8.3s}".format(num="Geeky"))
print("----------center align and fill with *----------")
print("{num:*^8.3s}".format(num="Geeky"))


print("----------(,)----------")
print("{:,}".format(1234567890))
print("----------(-)----------")
print("{:_}".format(1234567890))
print("----------(exprsion)----------")
print("{:.4}".format(50/3))
print("----------(%)----------")
print("{:.4%}".format(50/3))
print("---------agruments items----------")
value=[10,20]
print(value)
print("{0[0]} {0[1]}".format(value))
dic={1:2000,'b':"B"}
print(dic)
print("{0[1]} {0[b]}".format(dic))