# **********String Methods**********
s1="LAvanya"
s2="MIraman"
print("--------------upper()-----------")
print(s1.upper())
print("--------------lower()-----------")
print(s1.lower())
print("--------------swapcase()-----------")
print(s1.swapcase())
print("--------------title()-----------")
print("LAvanya kitra google".title())
print("--------------isupper()-----------")
s="LAVA"
s2="lava"
print("s1=",s1,"s2=",s2,"s=",s,)
print(s1.isupper())
print(s.isupper())
print("--------------islower()-----------")
print(s1.islower())
print(s2.islower())
print("--------------istitle()-----------")
print(s1.istitle())
print("--------------isdigit()-----------")
print("1234A".isdigit())
print("1234".isdigit())
print("--------------isalpha()-----------")
print(s1.isalpha())
print("1234A".isalpha())
print("--------------isalnum()-----------")
print("12123".isalnum())
print("hsgfhdsfg".isalnum())
print("$$%A".isalnum())
print("1232326Afhdf".isalnum())
print("--------------isspace()-----------")
print("      ".isspace())
print("         h ".isspace())
print("--------------lstrip()-----------")
print("        lava".lstrip())
print("lava                       ".lstrip(),end="")
print("LAvanya")
print("            lavamya       ".lstrip(),end="##")
print("\n--------------rstrip()-----------")
print("         llavanya         ".rstrip(),end="#")
print()
print("lavanya         lavnya         ".rstrip(),end="##")
print("\n--------------strip()-----------")
print("          hdsd       ".strip(),end="#")
print()
print("     kjhd".strip())
print("--------------replace()-----------")
print("Lavanya Mira".replace("Mira","Madhu"))
print("--------------split()-----------")
str="Lavanya nagesh miranam"
print(str)
t=(str.split())
print(t)
print("--------------join()-----------")
print(t)
print(" ".join(t))
print("--------------startwith()-----------")
print("Lavanyanya".startswith("Lavanya"))
print("Lah bsbd h".startswith("S"))
print("--------------endswith()-----------")
print("Lavanyanya".endswith("nya"))
print("hds dghsjd hdjs".endswith("Lavanya"))
print("--------------ord()-----------")
print(ord("A"))
print(ord("L"))
